/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prohor_translator_TranslatorService */

#ifndef _Included_com_prohor_translator_TranslatorService
#define _Included_com_prohor_translator_TranslatorService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prohor_translator_TranslatorService
 * Method:    nativeFunction
 * Signature: (Ljava/lang/String;[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_prohor_translator_TranslatorService_nativeFunction
  (JNIEnv *, jobject, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
